sweater:
  relations_types:
  - answers
  - negates
  - may be
  - means
  - therefore
  - includes
  chest:
    env:
      opts:
        sophia:
          path: /tmp/woollib/chest
        db:
          d: &ddbs
            compression: zstd
          i:
            *ddbs
          u:
            *ddbs
          o:
            *ddbs
  index:
    env:
      opts:
        sophia:
          path: /tmp/woollib/index
        db:
          t2o:
            *ddbs
          o2t:
            *ddbs
          i2t:
            *ddbs
          t2i:
            *ddbs
          i2o:
            *ddbs
          o2i:
            *ddbs
graph:
  dest: /tmp/sweater_graph.dot
  config:
    wrap_width: 40
    externalize_relations_nodes: none
    nodes_ids: mentioned
conversion:
  src: spec/batch.yml
