sweater:
  relations_types:
  - answers
  - negates
  - may be
  - means
  - therefore
  - includes
  chest:
    env:
      opts:
        sophia:
          path: /tmp/woollib/trove/data
        db:
          d: &ddbs
            compression: zstd
    index:
      env:
        opts:
          sophia:
            path: /tmp/woollib/trove/index
          db:
            t2o:
              *ddbs
            o2t:
              *ddbs
            d2v:
              *ddbs
            c:
              *ddbs
graph:
  dest: /tmp/sweater_graph.dot
  config:
    wrap_width: 40
    externalize_relations_nodes: none
    nodes_ids: mentioned
conversion:
  src: spec/batch.yml
